# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cervical-spine-fracture-detection',
                'doc_host': 'https://amaarora.github.io',
                'git_url': 'https://github.com/amaarora/cervical-spine-fracture-detection',
                'lib_path': 'cervical_spine_fracture_detection'},
  'syms': { 'cervical_spine_fracture_detection.core': { 'cervical_spine_fracture_detection.core.foo': ( 'core.html#foo',
                                                                                                        'cervical_spine_fracture_detection/core.py')}}}
